# Generated by Django 2.2.6 on 2020-04-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0003_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('consumer', 'consumer')], max_length=8),
        ),
    ]
