# Generated by Django 2.2.6 on 2020-04-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0005_auto_20200407_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('consumer', 'consumer')], max_length=8),
        ),
    ]
