# Generated by Django 2.2.6 on 2020-04-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0007_auto_20200411_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('consumer', 'consumer')], max_length=8),
        ),
    ]
