# Generated by Django 2.2.6 on 2020-04-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0009_auto_20200416_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('consumer', 'consumer'), ('staff', 'staff')], max_length=8),
        ),
    ]
