# Generated by Django 2.2.6 on 2020-04-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0010_auto_20200416_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('consumer', 'consumer')], max_length=8),
        ),
    ]
