# Generated by Django 2.2.6 on 2020-04-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0011_auto_20200418_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
